name: Build and Push Docker Images for Infra
on:
  repository_dispatch:
    types: [my-event]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v3
        
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Get Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: olawde/backend:${{ steps.timestamp.outputs.timestamp }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: olawde/frontend:${{ steps.timestamp.outputs.timestamp }}

  trigger-repo-b:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Success Event
        if: ${{ success() }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN_TO_TRIGGER }}
          repository: olawaleade/helm
          event-type: success-event
          client-payload: '{"message": "Build and push successful"}'